vince: Specify required instances in Device FCM
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.qti.hardware.perf@2.2::IPerf/default

Signed-off-by: anandhan07 <anandhasayanan007jb@gmail.com>